print('Anas Ahmed')
print('18B-116-cs')
print('LAb 09')
print('P.EX 02')

def distribution(file_name):
    infile = open(file_name,'r')
    words = infile.read()
    infile.close()
    print(words.count('A+'),'No of students got Grade A+')
    print(words.count('A'),'No of students got Grade A')
    print(words.count('A-'),'No of students got Grade A')
    print(words.count('B+'),'No of students got Grade B+')   
    print(words.count('B'),'No of students got Grade B')
    print(words.count('B-'),'No of students got Grade B-')
    print(words.count('C+'),'No of students got Grade C+')
    print(words.count('C'),'No of students got Grade C')
    print(words.count('C-'),'No of students got Grade C-')
    print(words.count('D+'),'No of students got Grade D+')
    print(words.count('D'),'No of students got Grade D')
    print(words.count('E'),'No of students got Grade E')
    print(words.count('F'),'No of students got Grade F')
distribution('Grades.txt')
