print('Anas Ahmed')
print('18B-116-cs')
print('LAb 09')
print('P.EX 01')

def stats(file_name):
    infile = open(file_name,'r')
    words = infile.read()
    infile = open(file_name,'r')
    lines = infile.readlines()
    total_lines = len(lines)
    wordlist = words.split()
    total_words = len(wordlist)
    letters = len(words)
    infile.close()
    print('Lines count: ',total_lines)
    print('Words count: ',total_words)
    print('Letters count: ',letters)
stats('AnasAhmed.txt')    
